# Lab | Numpy Deep Dive

### 1. Import the NUMPY package under the name np.


In [2]:
import numpy as np




### 2. Print the NUMPY version and the configuration.


In [4]:
np.__version__



'2.4.6'

### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable "a"
Challenge: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?


In [24]:
a = np.random.randint(10, size=(2,3,5))

a = np.random.randn(2,3,5)

a = np.random.rand(2,3,5)



### 4. Print a.


In [23]:
print(a)


[[[7 2 0 4 7]
  [9 0 5 1 6]
  [2 6 5 1 4]]

 [[6 9 9 8 5]
  [5 5 3 4 2]
  [3 1 5 0 5]]]


### 5. Create a 5x2x3 3-dimensional array with all values equaling 1.
### Assign the array to variable "b"


In [20]:
b = np.ones(shape=(5,2,3))



### 6. Print b.


In [21]:
print(b)


[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]



### 7. Do a and b have the same size? How do you prove that in Python code?


In [26]:
np.shape(a) == np.shape(b)


False


### 8. Are you able to add a and b? Why or why not?


In [31]:
try:
    np.add(a,b)

except:
    ValueError
    print("The arrays do not have the same shape. Hence, addition is not possible.")





The arrays do not have the same shape. Hence, addition is not possible.




### 9. Transpose b so that it has the same structure of a (i.e. become a 2x3x5 array). Assign the transposed array to varialbe "c".


In [38]:
c = np.transpose(b, axes=(1,2,0))

print(c)


[[[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]]



### 10. Try to add a and c. Now it should work. Assign the sum to variable "d". But why does it work now?


In [41]:
try: 
    d = np.add(a,c)
    print("The arrays have the same shape now. Hence, addition works.")
except:
    ValueError
    print("The arrays still don't have the same shape. Hence, no addition possible.")


The arrays have the same shape now. Hence, addition works.



### 11. Print a and d. Notice the difference and relation of the two array in terms of the values? Explain.


In [44]:
print(a)

print("........")

print(d)

print("Every value in d is exactly greater 1 than the value at the same position in a. That's how vector addition works.")


[[[0.01616971 0.02697853 0.13409276 0.29911356 0.61132068]
  [0.0190537  0.66446663 0.92207616 0.471084   0.95976948]
  [0.30191878 0.67009724 0.90824356 0.14082286 0.14952865]]

 [[0.8103117  0.87345414 0.98705014 0.82012615 0.81222863]
  [0.77130257 0.5751292  0.83943134 0.82992383 0.29520506]
  [0.66520256 0.06073426 0.01002127 0.57670154 0.00866805]]]
........
[[[1.01616971 1.02697853 1.13409276 1.29911356 1.61132068]
  [1.0190537  1.66446663 1.92207616 1.471084   1.95976948]
  [1.30191878 1.67009724 1.90824356 1.14082286 1.14952865]]

 [[1.8103117  1.87345414 1.98705014 1.82012615 1.81222863]
  [1.77130257 1.5751292  1.83943134 1.82992383 1.29520506]
  [1.66520256 1.06073426 1.01002127 1.57670154 1.00866805]]]
Every value in d is exactly greater 1 than the value at the same position in a. That's how vector addition works.



### 12. Multiply a and c. Assign the result to e.


In [46]:
e = np.multiply(a,c)




### 13. Does e equal to a? Why or why not?


In [50]:
if np.array_equal(a, e):
    print("Vector multiplication (as opposed to the scalar product) works element-wise. Hence, c is a matrix of ones.")
else:
    print("c is not a matrix of ones.")



Vector multiplication (as opposed to the scalar product) works element-wise. Hence, c is a matrix of ones.




### 14. Identify the max, min, and mean values in d. Assign those values to variables "d_max", "d_min", and "d_mean"


In [55]:
d_min = np.min(d)
d_max = np.max(d)
d_mean = np.mean(d)

print(d_min)
print(d_max)
print(d_mean)



1.0086680539560122
1.9870501396222315
1.5076742241981376



### 15. Now we want to label the values in d. First create an empty array "f" with the same shape (i.e. 2x3x5) as d using `np.empty`.


In [33]:
### [your code here]





### 16. Populate the values in f. For each value in d, if it's larger than d_min but smaller than d_mean, assign 25 to the corresponding value in f.
If a value in d is larger than d_mean but smaller than d_max, assign 75 to the corresponding value in f.
If a value equals to d_mean, assign 50 to the corresponding value in f.
Assign 0 to the corresponding value(s) in f for d_min in d.
Assign 100 to the corresponding value(s) in f for d_max in d.
In the end, f should have only the following values: 0, 25, 50, 75, and 100.
Note: you don't have to use Numpy in this question.



In [34]:
### [your code here]






### 17. Print d and f. Do you have your expected f?
For instance, if your d is:
array([[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
        [1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
        [1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],

       [[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
        [1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
        [1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]])

Your f should be:
array([[[ 75.,  75.,  75.,  25.,  75.],
        [ 75.,  75.,  25.,  25.,  25.],
        [ 75.,  25.,  75.,  75.,  75.]],

       [[ 25.,  25.,  25.,  25., 100.],
        [ 75.,  75.,  75.,  75.,  75.],
        [ 25.,  75.,   0.,  75.,  75.]]])



In [35]:
### [your code here]


### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), how to use string values 
("A", "B", "C", "D", and "E") to label the array elements? You are expecting the result to be:
array([[[ 'D',  'D',  'D',  'B',  'D'],
        [ 'D',  'D',  'B',  'B',  'B'],
        [ 'D',  'B',  'D',  'D',  'D']],

       [[ 'B',  'B',  'B',  'B',  'E'],
        [ 'D',  'D',  'D',  'D',  'D'],
        [ 'B',  'D',   'A',  'D', 'D']]])
Again, you don't need Numpy in this question.

In [36]:
### [your code here]